import Box from '@mui/material/Box';
import dynamic from 'next/dynamic';
const AccountSettingContainer = dynamic(
  () => import('@/pages_fsd/account-setting/components').then((module) => module.AccountSettingContainer),
  { ssr: false }
);

export const metadata = {
  title: '상담앱 관리자 | 계정 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <Box>
      <AccountSettingContainer />
    </Box>
  );
};

export default Page;
