import Box from '@mui/material/Box';
import AccountSettingBox from '@/features/dashboard/components/account-setting';
import Typography from '@mui/material/Typography';

export const metadata = {
  title: '상담앱 관리자 | 계정 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <Box>
      <Typography variant="h5">계정 설정</Typography>
      <AccountSettingBox />
    </Box>
  );
};

export default Page;
