import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export const metadata = {
  title: '상담앱 관리자 | 차트 데이터 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <Box>
      <Typography variant="h5">차트 설정</Typography>
    </Box>
  );
};

export default Page;
