import Box from '@mui/material/Box';

import { ManageContainer } from '@/pages_fsd/detail-page-data-manage/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 상세페이지 데이터 관리',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <ManageContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
