import Box from '@mui/material/Box';

import MojipDataManageContainer from '@/pages_fsd/mojip-data-manage/components/mojip-data-manage-container';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 상세페이지 데이터 관리',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <MojipDataManageContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
