options:
  size: 2x

pipelines:
  branches:
    main:
      - step:
          name: Build and Push to Harbor (Main Branch)
          deployment: Production
          script:
            - export IMAGE_NAME="${BITBUCKET_REPO_SLUG}"
            - docker build -t ${IMAGE_NAME} --build-arg NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL_REAL} --build-arg NEXT_PUBLIC_MOCKING=${NEXT_PUBLIC_MOCKING} .
            - echo $HARBOR_PASSWORD | docker login harbor-apply.jinhaksa.com/consulting --username $HARBOR_USERNAME --password-stdin
            - docker tag "${IMAGE_NAME}:latest" harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:main
            - docker push harbor-apply.jinhaksa.com/consulting/"${IMAGE_NAME}:main"
          services:
            - docker
          caches:
            - docker

    develop:
      - step:
          name: Build (Develop Branch)
          script:
            - export IMAGE_NAME="${BITBUCKET_REPO_SLUG}"
            - docker build -t ${IMAGE_NAME}:develop --build-arg NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL_TEST} --build-arg NEXT_PUBLIC_MOCKING=${NEXT_PUBLIC_MOCKING} .
          services:
            - docker
          caches:
            - docker

      - step:
          name: Push to Harbor (Develop Branch)
          deployment: Staging
          script:
            - export IMAGE_NAME="${BITBUCKET_REPO_SLUG}"
            - echo $HARBOR_PASSWORD | docker login harbor-apply.jinhaksa.com/consulting --username $HARBOR_USERNAME --password-stdin
            - docker tag "${IMAGE_NAME}:latest" harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:develop
            - docker push harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:develop
          services:
            - docker
          caches:
            - docker
