options:
  size: 2x

pipelines:
  branches:
    main:
      - step:
          name: Build and Push to Harbor (Main Branch)
          deployment: Production
          script:
            - export IMAGE_NAME="${BITBUCKET_REPO_SLUG}"
            - export DATE_TAG=$(date +%Y%m%d%H%M)
            - |
              docker build --progress=plain -t ${IMAGE_NAME} \
                --build-arg NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL_REAL} \
                --build-arg NEXT_PUBLIC_MOCKING=${NEXT_PUBLIC_MOCKING} \
                . > build_output.txt 2>&1 &
            - |
              while true; do
                sleep 20
                echo "Memory usage at $(date):"
                docker stats --no-stream --format "{{.MemUsage}}"
                echo "Available memory: $(free -h | awk '/^Mem:/ {print $7}')"
                if ! pgrep -f "docker build" > /dev/null; then
                  break
                fi
              done
            - echo $HARBOR_PASSWORD | docker login harbor-apply.jinhaksa.com/consulting --username $HARBOR_USERNAME --password-stdin
            - docker tag "${IMAGE_NAME}:latest" harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:main
            - docker tag "${IMAGE_NAME}:latest" harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:main_${DATE_TAG}
            - docker push harbor-apply.jinhaksa.com/consulting/"${IMAGE_NAME}:main"
            - docker push harbor-apply.jinhaksa.com/consulting/"${IMAGE_NAME}:main_${DATE_TAG}"
          services:
            - docker
          caches:
            - docker
    develop:
      - step:
          name: Build and Push to Harbor (Develop Branch)
          deployment: Staging
          script:
            - export IMAGE_NAME="${BITBUCKET_REPO_SLUG}"
            - export DATE_TAG=$(date +%Y%m%d%H%M)
            - docker build -t ${IMAGE_NAME} -f Dockerfile.dev --build-arg NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL_TEST} --build-arg NEXT_PUBLIC_MOCKING=${NEXT_PUBLIC_MOCKING} .
            - echo $HARBOR_PASSWORD | docker login harbor-apply.jinhaksa.com/consulting --username $HARBOR_USERNAME --password-stdin
            - docker tag "${IMAGE_NAME}:latest" harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:develop
            - docker tag "${IMAGE_NAME}:latest" harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:develop_${DATE_TAG}
            - docker push harbor-apply.jinhaksa.com/consulting/${IMAGE_NAME}:develop
            - docker push harbor-apply.jinhaksa.com/consulting/"${IMAGE_NAME}:develop_${DATE_TAG}"
          services:
            - docker
          caches:
            - docker
