pipelines:
  branches:
    main:
      import: consulting-admin-server:master:common-pipeline-production
    develop:
      import: consulting-admin-server:develop:common-pipeline-test
  custom:
    1-deploy-test:
      import: consulting-admin-server:develop:common-pipeline-test
    2-deploy-production:
      import: consulting-admin-server:master:common-pipeline-production
