import Box from '@mui/material/Box';

import MojipSettingContainer from '@/pages_fsd/detail-page-setting/components/detail-page-setting-container';
import MojipSettingProvider from '@/pages_fsd/detail-page-setting/contexts';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 상세페이지 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <MojipSettingProvider>
        <Box>
          <MojipSettingContainer />
        </Box>
      </MojipSettingProvider>
    </UnivServiceCheckGuard>
  );
};

export default Page;
