import Box from '@mui/material/Box';

import { DetailPageSettingContainer } from '@/pages_fsd/detail-page-setting/components';
import { DetailPageSettingProvider } from '@/pages_fsd/detail-page-setting/contexts';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 상세페이지 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <DetailPageSettingProvider>
        <Box>
          <DetailPageSettingContainer />
        </Box>
      </DetailPageSettingProvider>
    </UnivServiceCheckGuard>
  );
};

export default Page;
