import Box from '@mui/material/Box';

import { DetailPageSettingContainer } from '@/pages_fsd/detail-page-setting/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 상세페이지 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <DetailPageSettingContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
