import MojipSettingBox from '@/features/dashboard/components/mojip-setting';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export const metadata = {
  title: '상담앱 관리자 | 모집요강 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <Box>
      <Typography variant="h5">모집요강 설정</Typography>

      <MojipSettingBox />
    </Box>
  );
};

export default Page;
