import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import CalendarBox from '@/features/schedule-setting/components/calendar-box';
import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';

export const metadata = {
  title: '상담앱 관리자 | 스케줄 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">스케줄 설정</Typography>
        <CalendarBox />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
