import Box from '@mui/material/Box';

import { EtcLibraryContainer } from '@/pages_fsd/etc-library/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 기타 자료실',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <EtcLibraryContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
