import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export const metadata = {
  title: '상담앱 관리자 | 학과 자료 업로드',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">학과 자료 업로드</Typography>
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
