import Box from '@mui/material/Box';

import { AppDeployContainer } from '@/pages_fsd/app-deploy/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 앱 배포',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <AppDeployContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
