import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

export const metadata = {
  title: '상담앱 관리자 | 상담앱 통계',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <Container>
      <Typography variant="h5">상담앱 통계</Typography>
    </Container>
  );
};

export default Page;
