import { setDuplicateSetting } from '@/features/flutter-setting/apis/set-duplicate-setting';

export const API_URLS = {
  user: {
    signin: '/auth/login',
    profile: '/auth/profile',
    updateProfileImage: '/user/profile/upload',
  },
  dashboard: {
    getConsultingAppState: '/admin/service-detail',
    getConsultingAppStateAll: '/admin/service-detail-all',
    updateConsultingAppState: '/admin/service-detail/current-state',
    syncMoaNesinService: '/admin/sync-moa-nesin-service',
    createService: '/foundation/service/create',
    updateIsNew: '/foundation/service/update-is-new',
    versionList: '/foundation/cur-tbl-version',
    foundationLibrary: '/file/foundation-library',
    foundationLibraryFileOnly: '/file/foundation-library-file-only',
    etcLibrary: '/file/etc-library',
    deployApp: '/deploy/deploy-app',
    deployTestData: '/foundation/sync-from-test',
    syncFromTestToDev: '/foundation/sync-from-test-to-dev',
    getAppVersionHistory: '/deploy/version-update-history',
    getAppDownloadUrl: '/deploy/download',
    getConsultingFileList: 'reflibrary/',
    downloadConsultingFile: 'reflibrary/download',
    uploadConsultingFile: 'reflibrary/upload',
    updateConsultingRefTitle: 'reflibrary/update-reftitle',
    updateConsultingRefNo: 'reflibrary/update-refno',
    chartData: '/app-setup/chartdata',
    deleteConsultingFile: 'reflibrary/delete',
    detailpage: '/app-setup/detailpage',
    updateDetailpageData: '/app-setup/detailpage/bulk',
    duplicateDetailpage: '/app-setup/detailpage/duplicate',
    syncDetailpage: '/app-setup/sync/detailpage',
    getFlutterCategory: '/custom-config/category',
    getFlutterRowInfo: '/custom-config/rows-info-hierarchy',
    flutterCustomConfig: '/custom-config',
    setDuplicateSetting: '/custom-config/duplicate',
    uploadMajorFile: '/subject/upload',
    getbrowserFile: '/file/browse',
    downloadBrowserFile: '/file/download',
    deleteBrowserFile: '/file/delete',
    renameBrowserFile: '/file/rename',
  },
  admin: {
    getUnivList: '/admin/univlist',
    getServiceList: '/admin/service',
  },
};
