export const PATHS = {
  home: '/',
  auth: {
    signIn: '/auth/sign-in',
  },
  dashboard: {
    overview: '/dashboard/overview',
    serviceSetting: '/dashboard/service-setting',
    versionSetting: '/dashboard/version-setting',
    consultingFileSetting: '/dashboard/consulting-file-setting',
    excelUpload: '/dashboard/foundation-upload',
    mojipSetting: '/dashboard/mojip-setting',
    mojipDataManage: '/dashboard/mojip-data-manage',
    chartSetting: '/dashboard/chart-setting',
    scheduleSetting: '/dashboard/schedule-setting',
    flutterUserSettigs: '/dashboard/flutter-setting',
    consultingStatistic: '/dashboard/consulting-statistic',
    excelLibrary: '/dashboard/foundation-library',
    accountSetting: '/dashboard/account-setting',
    appDeploy: '/dashboard/app-deploy',
    appVersionHistory: '/dashboard/app-version-history',
    dataDeploy: '/dashboard/data-deploy',
    etcFiles: '/dashboard/etc-library',
    majorFileLibrary: '/dashboard/major-file-library',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
