import Box from '@mui/material/Box';

import { ServiceSettingContainer } from '@/pages_fsd/service-setting/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 서비스 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard checkService={false}>
      <Box>
        <ServiceSettingContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
