import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import ServiceSettingContainer from '@/features/service-setting/components/service-setting-container';
import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';

export const metadata = {
  title: '상담앱 관리자 | 서비스 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard checkService={false}>
      <Box>
        <Typography variant="h5">서비스 설정</Typography>
        <ServiceSettingContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
