import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import ServiceSettingBox from '@/features/dashboard/components/service-setting';

export const metadata = {
  title: '상담앱 관리자 | 서비스 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Container>
        <Typography variant="h5">서비스 설정</Typography>
        <ServiceSettingBox />
      </Container>
    </UnivServiceCheckGuard>
  );
};

export default Page;
