import Grid from '@mui/material/Unstable_Grid2';
import Typography from '@mui/material/Typography';

import ExcelUploader from '@/features/dashboard/components/excel-uploader';

export const metadata = {
  title: '상담앱 관리자 | 기초 엑셀 업로드',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <Grid container spacing={3}>
      <Grid>
        <Typography variant="h5">기초 데이터 엑셀 업로드</Typography>
        <ExcelUploader />
      </Grid>
    </Grid>
  );
};

export default Page;
