import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import ExcelUploader from '@/features/dashboard/components/excel-upload/excel-uploader';

export const metadata = {
  title: '상담앱 관리자 | 기초 엑셀 업로드',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Container>
        <Typography variant="h5">기초 데이터 엑셀 업로드</Typography>
        <ExcelUploader />
      </Container>
    </UnivServiceCheckGuard>
  );
};

export default Page;
