import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import EtcFileLibraryListBox from '@/features/dashboard/components/etc-files';
import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';

export const metadata = {
  title: '상담앱 관리자 | 기타 자료실',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">기타 자료실</Typography>
        <EtcFileLibraryListBox />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
