import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import VersionSettingBox from '@/features/dashboard/components/version-setting';

export const metadata = {
  title: '상담앱 관리자 | 버전 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">버전 설정</Typography>
        <VersionSettingBox />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
