import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import MSWProvider from '@/shared/components/providers/MSWProvider';
import QueryProvider from '@/shared/components/providers/QueryProvider';
import AppThemeProvider from '@/shared/components/providers/ThemeProvider';
import UserProvider from '@/features/auth/contexts/user-context';
import UnivServiceProvider from '@/shared/contexts/univ-service-context';
import '@/shared/style/css/reset.css';
import '@/shared/style/css/animation.css';

export const metadata = {
  title: '상담앱 관리자',
  description: 'Generated by Next.js',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="kor">
      <body>
        <MSWProvider>
          <QueryProvider>
            <UserProvider>
              <UnivServiceProvider>
                <AppRouterCacheProvider>
                  <AppThemeProvider>{children}</AppThemeProvider>
                </AppRouterCacheProvider>
              </UnivServiceProvider>
            </UserProvider>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
};

export default RootLayout;
