import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import MSWProvider from "@/shared/components/providers/MSWProvider";
import QueryProvider from "@/shared/components/providers/QueryProvider";
import AppThemeProvider from "@/shared/components/providers/ThemeProvider";
import UserProvider from "@/features/auth/context/user-context";
import "@/shared/style/reset.css";

export const metadata = {
  title: "Consulting-Admin",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="kor">
      <body>
        <MSWProvider>
          <QueryProvider>
            <UserProvider>
              <AppRouterCacheProvider>
                <AppThemeProvider>{children}</AppThemeProvider>
              </AppRouterCacheProvider>
            </UserProvider>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
};

export default RootLayout;
