import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import QueryProvider from "@/shared/components/providers/QueryProvider";
import AppThemeProvider from "@/shared/components/providers/ThemeProvider";
import UserProvider from "@/features/auth/context/user-context";
import "@/shared/style/reset.css";

export const metadata = {
  title: "Consulting-Admin",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="kor">
      <body>
        <QueryProvider>
          <UserProvider>
            <AppRouterCacheProvider>
              <AppThemeProvider>{children}</AppThemeProvider>
            </AppRouterCacheProvider>
          </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
