import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import CalculationSettingContainer from '@/pages_fsd/calculation-setting/components/calculation-setting-container';
import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';

export const metadata = {
  title: '상담앱 관리자 | 성적 계산 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <CalculationSettingContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
