import Box from '@mui/material/Box';

import { FoundationUploadContainer } from '@/pages_fsd/foundation-upload/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 기초데이터 업로드',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <FoundationUploadContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
