import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import DataDeployBox from '@/features/dashboard/components/data-deploy';

export const metadata = {
  title: '상담앱 관리자 | 데이터 배포',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">데이터 배포</Typography>
        <DataDeployBox />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
