import Box from '@mui/material/Box';

import { DataDeployContainer } from '@/pages_fsd/data-deploy/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 데이터 배포',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <DataDeployContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
