import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import MojipDataManageContainer from '@/features/mojip-data-manage/components/mojip-data-manage-container';
import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';

export const metadata = {
  title: '상담앱 관리자 | 모집요강 데이터 관리',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">모집요강 데이터 관리</Typography>
        <MojipDataManageContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
