import { ConsultingAppState } from '../../types/consultingapp-state.type';

export const dummyConsultingAppStates: ConsultingAppState[] = [
  {
    univID: '9998',
    serviceID: '999825',
    univName: '진학대학교',
    developer: 'Kafka',
    manager: '류수현',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: true,
    currentState: 'developing',
  },
  {
    univID: '3017',
    serviceID: '301703',
    univName: '동국대학교',
    developer: '유수현',
    manager: '류수현',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: false,
    currentState: 'testing',
  },
  {
    univID: '1017',
    serviceID: '101704',
    univName: '국민대학교',
    developer: '유수현',
    manager: '류수현',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: true,
    currentState: 'dataRequested',
  },
  {
    univID: '8765',
    serviceID: '876543',
    univName: '서울대학교',
    developer: 'Kafka',
    manager: '박영희',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: false,
    currentState: 'deployed',
  },
  {
    univID: '4321',
    serviceID: '432109',
    univName: '연세대학교',
    developer: '이영수',
    manager: '최민지',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: true,
    currentState: 'running',
  },
  {
    univID: '7890',
    serviceID: '789012',
    univName: '고려대학교',
    developer: '박철수',
    manager: '김영희',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: false,
    currentState: 'testing',
  },
  {
    univID: '2468',
    serviceID: '246813',
    univName: '성균관대학교',
    developer: '최영수',
    manager: '이민지',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: true,
    currentState: 'developing',
  },
  {
    univID: '1357',
    serviceID: '135724',
    univName: '한양대학교',
    developer: '김민수',
    manager: '박지영',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: false,
    currentState: 'dataRequested',
  },
  {
    univID: '9876',
    serviceID: '987654',
    univName: '중앙대학교',
    developer: '이철수',
    manager: '최은지',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: true,
    currentState: 'running',
  },
  {
    univID: '5432',
    serviceID: '543210',
    univName: '경희대학교',
    developer: '박영수',
    manager: '김민지',
    serviceYear: '2024',
    serviceType: 'susi',
    isNew: false,
    currentState: 'testing',
  },
  {
    univID: '1098',
    serviceID: '109876',
    univName: '서강대학교',
    developer: '최철수',
    manager: '둘리',
    serviceYear: '2024',
    serviceType: 'jungsi',
    isNew: true,
    currentState: 'running',
  },
];
