import SignInForm from '@/features/auth/components/sign-in-form';

export const metadata = {
  title: '상담앱 관리자 | 로그인',
  description: 'Generated by Next.js',
};

const Page = () => {
  return <SignInForm />;
};

export default Page;
