import Layout from '@/features/auth/components/layout';
import SignInForm from '@/features/auth/components/sign-in-form';
import GuestGuard from '@/features/auth/components/guest-guard';

export const metadata = {
  title: '상담앱 관리자 | 로그인',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <GuestGuard>
      <Layout>
        <SignInForm />
      </Layout>
    </GuestGuard>
  );
};

export default Page;
