import Box from '@mui/material/Box';

import { MajorFileLibraryContainer } from '@/pages_fsd/major-file-library/components';
import { UnivServiceCheckGuard } from '@/shared/components';

export const metadata = {
  title: '상담앱 관리자 | 학과 자료실',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <MajorFileLibraryContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
