import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import MajorFileLibraryContainer from '@/features/major-file-library/components/major-file-library-container';

export const metadata = {
  title: '상담앱 관리자 | 학과 자료실',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">학과 자료실</Typography>
        <MajorFileLibraryContainer />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
