import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';

export const metadata = {
  title: '상담앱 관리자 | 앱 사용자 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">앱 사용자 설정</Typography>
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
