import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import FlutterSettingContainer from '@/features/flutter-setting/components/flutter-setting-container';
import FlutterSettingProvider from '@/features/flutter-setting/contexts';

export const metadata = {
  title: '상담앱 관리자 | 앱 사용자 설정',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <FlutterSettingProvider>
        <Box>
          <Typography variant="h5">앱 사용자 설정</Typography>
          <FlutterSettingContainer />
        </Box>
      </FlutterSettingProvider>
    </UnivServiceCheckGuard>
  );
};

export default Page;
