export const DATA_TYPES = [
  'MajorNo',
  'CourseNo',
  'CourseName',
  'SubjectNo',
  'SubjectName',
  'SubjectDescriptionLink',
  'SelTypeNo',
  'SelTypeName',
  'CollegeNo',
  'CollegeName',
  'GunChasuNo',
  'GunChasuName',
  'ETC1',
  'ETC2',
  'ETC3',
  'ETC4',
  'ETC5',
  'SATCalcCaseNo',
  'SATConstCaseNo',
  'HSBCalcCaseNo',
  'LastYearApplyRatio',
  'LastYearJiwonCnt',
  'LastYearMojipCnt',
  'BeforeTwoYearApplyRatio',
  'BeforeTwoYearJiwonCnt',
  'BeforeTwoYearMojipCnt',
  'BeforeThreeYearApplyRatio',
  'BeforeThreeYearJiwonCnt',
  'BeforeThreeYearMojipCnt',
  'PersonalCnt',
  'SATPercent',
  'myScore',
  'scoreDiff',
  'diagnosis',
  'HSBMaxScore',
  'HSBMinScore',
  'HSBAvgScore',
  'SATMaxScore',
  'SATMinScore',
  'SATAvgScore',
  'TOTMaxScore',
  'TOTMinScore',
  'TOTAvgScore',
  'SATTopLevelMinCut',
  'SATHighLevelMinCut',
  'SATMiddleLevelMinCut',
  'IsAllowKorA',
  'IsAllowKorB',
  'IsAllowEngA',
  'IsAllowEngB',
  'IsAllowMatA',
  'IsAllowMatB',
  'IsAllowMatC',
  'IsAllowSoc',
  'IsAllowSci',
  'IsAllowJob',
];

export const COMPARISON_OPERATORS = {
  EQ: '==',
  NE: '!=',
  GT: '>',
  GE: '>=',
  LT: '<',
  LE: '<=',
};
