import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

import ConsultingAppStateProvider from '@/features/dashboard/contexts/consultingapp-state-context';
import ConsultingAppStateBoard from '@/features/dashboard/components/overview/consultingapp-state-board';

export const metadata = {
  title: '상담앱 관리자 | 홈',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <ConsultingAppStateProvider>
      <Container>
        <Accordion slotProps={{ transition: { unmountOnExit: true } }} defaultExpanded>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="consultingapp-states-content"
            id="consultingapp-states-content"
          >
            <Typography variant="h5">입학상담앱 담당자 및 현황</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <ConsultingAppStateBoard />
          </AccordionDetails>
        </Accordion>
      </Container>
    </ConsultingAppStateProvider>
  );
};

export default Page;
