import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import AppHistoryListBox from '@/features/dashboard/components/app-version-history';

export const metadata = {
  title: '상담앱 관리자 | 앱 다운로드 정보',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Box>
        <Typography variant="h5">상담앱 다운로드 정보</Typography>
        <AppHistoryListBox />
      </Box>
    </UnivServiceCheckGuard>
  );
};

export default Page;
