import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

import UnivServiceCheckGuard from '@/shared/components/guards/univ-service-check-guard';
import AppHistoryListBox from '@/features/dashboard/components/app-version-history';

export const metadata = {
  title: '상담앱 관리자 | 앱 버전 히스토리',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <UnivServiceCheckGuard>
      <Container>
        <Typography variant="h5">상담앱 버전 히스토리</Typography>
        <AppHistoryListBox />
      </Container>
    </UnivServiceCheckGuard>
  );
};

export default Page;
