import dynamic from 'next/dynamic';
const ConsultingAppStateProvider = dynamic(
  () => import('@/features/overview/contexts').then((module) => module.default),
  { ssr: false }
);
const ConsultingAppStateBoard = dynamic(
  () => import('@/features/overview/components/consultingapp-state-board').then((module) => module.default),
  { ssr: false }
);

export const metadata = {
  title: '상담앱 관리자 | 홈 - 현황판',
  description: 'Generated by Next.js',
};

const Page = () => {
  return (
    <ConsultingAppStateProvider>
      <ConsultingAppStateBoard />
    </ConsultingAppStateProvider>
  );
};

export default Page;
