import { ProgressBoard } from '@/pages_fsd/overview/components';

export const metadata = {
  title: '상담앱 관리자 | 홈 - 현황판',
  description: 'Generated by Next.js',
};

const Page = () => {
  return <ProgressBoard />;
};

export default Page;
